# Generated by Django 4.2.4 on 2023-08-12 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('black_list_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('blocked_user_id', models.BigIntegerField(unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
