# Generated by Django 4.2.4 on 2023-08-11 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "market_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("market_name", models.CharField(max_length=30)),
                ("street_address", models.CharField(max_length=50)),
                ("postal_address", models.CharField(max_length=50)),
                ("has_toilet", models.BooleanField()),
                ("has_parking", models.BooleanField()),
                (
                    "favourite_markets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_favorite_markets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
