# Generated by Django 4.2.4 on 2023-08-09 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('market_name', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=50)),
                ('postal_address', models.CharField(max_length=50)),
                ('has_toilet', models.BooleanField()),
                ('has_parking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_address', models.CharField(max_length=50)),
                ('selling_products', models.CharField(max_length=30)),
                ('opening_time', models.CharField(max_length=10)),
                ('closing_time', models.CharField(max_length=10)),
                ('opening_frequency', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.market')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
