# Generated by Django 4.2.4 on 2023-08-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shop', '0002_alter_shop_market_id_delete_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='market_id',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ManyToManyField(related_name='shop_selling_product', to='products.product'),
        ),
    ]
