# Generated by Django 4.2.4 on 2023-08-16 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_alter_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='favourites',
            field=models.ManyToManyField(related_name='user_shop_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
