# Generated by Django 4.2.4 on 2023-08-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_alter_shop_market_id_delete_market'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('board_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('market_name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardPhoto',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=2750)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boards.board')),
            ],
        ),
    ]
