# Generated by Django 4.2.4 on 2023-08-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='purchased_products',
            field=models.ManyToManyField(related_name='board_purchased_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='board',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
