# Generated by Django 4.2.4 on 2023-08-16 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_alter_board_created_at_alter_board_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(related_name='liked_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
