# Generated by Django 4.2.4 on 2023-08-16 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_board_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
