# Generated by Django 4.2.4 on 2023-08-16 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_alter_board_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
