# Generated by Django 4.2.4 on 2023-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_board_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
